### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [nikodemus/screamer#17]
Please consider adding :description, :author and :license information to your ASDF system. This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by rpgoldman** [comment]
While you're doing that, it would be great to add a `:VERSION` tag.  Then if any major feature is added, a dependent system could check to make sure the right Screamer version is present. Just a simple
    
    (:VERSION "1.0")

would be great.

**Comment by nikodemus** [comment]
4.0.0 it is.
